# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-12-27 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者的 ID')),
                ('sid', models.IntegerField(verbose_name='被滑动者的 ID')),
                ('stype', models.CharField(choices=[('like', '右滑'), ('superlike', '上滑'), ('dislike', '左滑')], max_length=10, verbose_name='滑动类型')),
                ('stime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
